name: Build

on:
  pull_request:
  push:
    branches: [ 'main', 'develop' ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  CMake:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-13, windows-2022 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Environment Variables
        run: |
          TARGET_PATH=target/release
          echo "TARGET_PATH=$TARGET_PATH" >> $GITHUB_ENV

      - name: Prepare
        run: |
          mkdir -p "${{ env.TARGET_PATH }}"

      - name: Configure
        run: |
          cd "${{ env.TARGET_PATH }}"
          cmake ../../

      - name: Build
        run: |
          cd "${{ env.TARGET_PATH }}"
          cmake --build . --parallel 4
